### ISSUE TITLE
云函数海底掘金运行错误

### ISSUE THREAD

**Issue by Thund1R** [ZiuChen/juejin-helper-SCF#14]
![360截图1685081888136114](https://user-images.githubusercontent.com/31063519/181905048-6ef85c14-a1da-498b-9d80-0ae3ebb12eea.png)
签到正常完成，海底掘金游戏运行一阵子就报错，所有配置都是按照要求配置的。

**Comment by ZiuChen** [comment]
* 是偶尔有一次报错，还是每天运行时都会报错？
  * 偶尔一次的情况：我部署的偶尔也会失败一次这时需要人工进游戏，手动把当前地图结束掉，之后让脚本重新跑就可以了
  * 如果是每天运行时都会报错，需要检查一下：
    * 是否授权了海底掘金游戏，如果没授权请到：[如何授权海底掘金游戏](https://github.com/iDerekLi/juejin-helper#%E5%A6%82%E4%BD%95%E6%8E%88%E6%9D%83%E6%B5%B7%E5%BA%95%E6%8E%98%E9%87%91%E6%B8%B8%E6%88%8F)授权一下

**Comment by Thund1R** [comment]
前几天每天都报错，今天又正常了:sweat_smile:

**Comment by ZiuChen** [comment]
> 前几天每天都报错，今天又正常了😅

😢
