### ISSUE TITLE
发表文章功能没有成功

### ISSUE THREAD

**Issue by loveme1573** [ZiuChen/juejin-helper-SCF#23]
发表文章功能没有成功 从10号开始的  什么都没提示

日志

今日已完成签到

今日已经沾过喜气

收集Bug +2

连续签到天数 4

累计签到天数 4

当前矿石数 9257

当前未消除Bug数量 294

当前幸运值 90/6000

预测All In矿石累计幸运值比率 30.62%

抽奖总次数 0

免费抽奖次数 0

今日限制矿石数 1500

今日获取已达上限

---开始任务：<发布一篇文章> ---

掘金成长

任务完成: 46.6

**Comment by ZiuChen** [comment]
我也遇到了这个问题。
刚刚简单看了一下，是segmentfault不让爬文章了。
这部分的代码可能需要修改一下 😥

**Comment by loveme1573** [comment]
> 我也遇到了这个问题。 刚刚简单看了一下，是segmentfault不让爬文章了。 这部分的代码可能需要修改一下disappointed_relieved

但是https://github.com/chinjiaqing/juejin-helper它就可以  有点东西啊

**Comment by ZiuChen** [comment]
> > 我也遇到了这个问题。 刚刚简单看了一下，是segmentfault不让爬文章了。 这部分的代码可能需要修改一下disappointed_relieved
> 
> 但是[https://github.com/chinjiaqing/juejin-helper它就可以](https://github.com/chinjiaqing/juejin-helper%E5%AE%83%E5%B0%B1%E5%8F%AF%E4%BB%A5) 有点东西啊

原理不同，原仓库使用无头浏览器puppeteer爬文章。
而云函数下puppeteer运行有一些问题，所以此仓库用的是直接发包爬取文章数据的。

**Comment by loveme1573** [comment]
> > > 我也遇到了这个问题。 刚刚简单看了一下，是segmentfault不让爬文章了。 这部分的代码可能需要修改一下disappointed_relieved
> > 
> > 
> > 但是[https://github.com/chinjiaqing/juejin-helper它就可以](https://github.com/chinjiaqing/juejin-helper%E5%AE%83%E5%B0%B1%E5%8F%AF%E4%BB%A5) 有点东西啊
> 
> 原理不同，原仓库使用无头浏览器puppeteer爬文章。 而云函数下puppeteer运行有一些问题，所以此仓库用的是直接发包爬取文章数据的。

https://segmentfault.com 好像增加了第一次访问滑块验证  估计得换网站了
